version: 1
pipeline:
  name: csv-to-csv-pipeline
  description: CSV 파일에서 CSV 파일로 데이터를 변환하는 파이프라인
  source:
    type: csv
    config:
      file_path: /Users/judongseok/Desktop/DataEngineer/jude-open-source/test_pipeline/data/sample_data.csv
      delimiter: ","
  destination:
    type: csv
    config:
      file_path: /Users/judongseok/Desktop/DataEngineer/jude-open-source/test_pipeline/data/output.csv
      delimiter: ","
      if_exists: replace
  variables:
    batch_size: 50
  logging:
    level: INFO
    file: pipeline.log 