version: 1
pipeline:
  name: csv-transform-mysql
  description: "CSV 파일에서 데이터를 추출하여 SQL로 변환 후 MySQL에 적재"
  
  source:
    type: csv
    config:
      file_path: "test_pipeline/data/sales.csv"
      delimiter: ","
      encoding: "utf-8"
      header: true
      parse_dates: ["order_date"]
      dtype:
        order_id: "int64"
        customer_id: "int64"
        amount: "float64"
  
  transformer:
    type: sql
    config:
      engine: "sqlite"
      temp_table: "sales_data"
      query: "SELECT customer_id, SUM(amount) as total_amount, 
              COUNT(*) as order_count, 
              MAX(order_date) as last_order_date 
              FROM sales_data 
              GROUP BY customer_id
              HAVING SUM(amount) > 100.0"
  
  destination:
    type: mysql
    config:
      host: ${MYSQL_HOST}
      port: 3306
      database: sales_db
      user: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      table: customer_summary
      if_exists: replace 